[package]
name = "aoc-2025"
version = "0.0.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
bitset = "0.1.2"
itertools = "0.14.0"
pathfinding = "4.14.0"
petgraph = { version = "0.8.3", features = ["rayon"] }
rayon = "1.11.0"
z3 = "0.19.5"
